---
fixtures:
  symlinks:
    dhcp: "#{source_dir}"
    common: "#{source_dir}/../common"
    concat: "#{source_dir}/../concat"
    iptables: "#{source_dir}/../iptables"
    logrotate: "#{source_dir}/../logrotate"
    rsync: "#{source_dir}/../rsync"
    rsyslog: "#{source_dir}/../rsyslog"
    stdlib: "#{source_dir}/../stdlib"
